### ISSUE TITLE
PlatformException(error, java.lang.IllegalStateException:

### ISSUE THREAD

**Issue by mz-myfc** [flutter-package/flutter_scan#57]
Flutter doesn't work after upgrading to 3.3.1, please update.

Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Unexpected platform view context. When constructing a platform view in the factory, use the context from PlatformViewFactory

**Comment by manoj-gslab** [comment]
+1

**Comment by mz-myfc** [comment]
Solution: After importing Git in the following way, it can be used perfectly. (Flutter 3.3.0 & 3.3.1 & 3.3.2)
Github: https://github.com/xiaoxie/flutter_scan

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  scan:
    git:
      url: https://github.com/xiaoxie/flutter_scan.git
      ref: main
```
